apiVersion: 1

datasources:

- name: Prometheus
  type: prometheus
  access: proxy
  url: http://algomon-prometheus:9090 
  orgId: 1
  isDefault: true
  uid: prometheus

- name: Elasticsearch
  type: elasticsearch
  access: proxy
  url: http://algomon-elasticsearch:9200
  orgId: 1
  uid: elasticsearch
  jsonData:
    index: 'stable-mainnet-v1.0'
    interval: Daily
    timeField: '@timestamp'
